#pragma once

#include "Core/Application.hpp"
#include "Core/FrameStats.hpp"
#include "Core/GameTimer.hpp"
#include "Core/Input.hpp"
#include "Core/Logger.hpp"
#include "Core/ResourceManager.hpp"

#include "Editor/Editor.hpp"

#include "Graphics/Allocator.hpp"
#include "Graphics/Buffer.hpp"
#include "Graphics/CommandList.hpp"
#include "Graphics/CommandQueue.hpp"
#include "Graphics/Constants.hpp"
#include "Graphics/DebugLayer.hpp"
#include "Graphics/Descriptor.hpp"
#include "Graphics/DescriptorHeap.hpp"
#include "Graphics/Device.hpp"
#include "Graphics/FrameResource.hpp"
#include "Graphics/GraphicsCommandList.hpp"
#include "Graphics/PipelineState.hpp"
#include "Graphics/ResourceUpload.hpp"
#include "Graphics/Resources.hpp"
#include "Graphics/RootSignature.hpp"
#include "Graphics/ShaderCompiler.hpp"
#include "Graphics/Texture.hpp"
#include "Graphics/Transform.hpp"
#include "Graphics/Utilities.hpp"
#include "Graphics/Window.hpp"

#include "Renderer/FinalRenderPass.hpp"
#include "Renderer/ForwardRenderer.hpp"
#include "Renderer/RenderLayer.hpp"
#include "Renderer/SkyboxRenderPass.hpp"

#include "Scene/Camera.hpp"
#include "Scene/Lights.hpp"
#include "Scene/Material.hpp"
#include "Scene/Mesh.hpp"
#include "Scene/RenderObject.hpp"
#include "Scene/Scene.hpp"
#include "Scene/ScreenQuad.hpp"
#include "Scene/Vertex.hpp"